
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSNAME NUMBER PLUS MINUS TIMES DIVIDE EQUALS LPAREN RPARENstatement : NAME EQUALS expressionstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'MINUS':([0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[3,7,3,3,-10,-9,3,3,3,3,-7,-10,7,3,-4,-3,-5,-6,-8,7,]),'PLUS':([1,5,6,11,12,13,15,16,17,18,19,20,],[8,-10,-9,-7,-10,8,-4,-3,-5,-6,-8,8,]),'DIVIDE':([1,5,6,11,12,13,15,16,17,18,19,20,],[10,-10,-9,-7,-10,10,10,10,-5,-6,-8,10,]),'LPAREN':([0,3,4,7,8,9,10,14,],[4,4,4,4,4,4,4,4,]),'NAME':([0,3,4,7,8,9,10,14,],[5,12,12,12,12,12,12,12,]),'NUMBER':([0,3,4,7,8,9,10,14,],[6,6,6,6,6,6,6,6,]),'RPAREN':([6,11,12,13,15,16,17,18,19,],[-9,-7,-10,19,-4,-3,-5,-6,-8,]),'TIMES':([1,5,6,11,12,13,15,16,17,18,19,20,],[9,-10,-9,-7,-10,9,9,9,-5,-6,-8,9,]),'EQUALS':([5,],[14,]),'$end':([1,2,5,6,11,12,15,16,17,18,19,20,],[-2,0,-10,-9,-7,-10,-4,-3,-5,-6,-8,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,7,8,9,10,14,],[1,11,13,15,16,17,18,20,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','r2python.py',67),
  ('statement -> expression','statement',1,'p_statement_expr','r2python.py',72),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','r2python.py',77),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','r2python.py',78),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','r2python.py',79),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','r2python.py',80),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','r2python.py',92),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','r2python.py',97),
  ('expression -> NUMBER','expression',1,'p_expression_number','r2python.py',102),
  ('expression -> NAME','expression',1,'p_expression_name','r2python.py',107),
]
